AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-video-thumbnails

  Sample SAM Template for serverless-video-thumbnails

Parameters:
  VideosBucketName:
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."
  EFSpath:
    Type: String
    Default: /mnt/efs
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-c3677dbf
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
    Default: subnet-1c8b6354,subnet-b80953e3
  AccessPointID:
    Type: String
    Description: Access point ID
    Default: fsap-09841f6b8b4e36be8
  FileSystemID:
    Type: String
    Description: EFS File System ID
    Default: fs-63b65743

Resources:
  FFmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ffmpeg_layer
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: makefile

  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thumbnail_function/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          EFS_PATH: !Ref EFSpath
      Layers:
        - !Ref FFmpegLayer
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref VideosBucketName
      - S3WritePolicy:
          BucketName: !Ref VideosBucketName
      - EFSWriteAccessPolicy:
          FileSystem: !Ref FileSystemID
          AccessPoint: !Ref AccessPointID
      Events:
        S3NewObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref VideosBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".mp4"
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
      - Arn: !Sub "arn:${AWS::Partition}:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:access-point/${AccessPointID}"
        LocalMountPath: !Ref EFSpath

  VideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref VideosBucketName
